feature: add wrapper step to vigilcd-ci.yml

diff --git a/.github/workflows/vigilcd-ci.yml b/.github/workflows/vigilcd-ci.yml
--- a/.github/workflows/vigilcd-ci.yml
+++ b/.github/workflows/vigilcd-ci.yml
@@ -61,3 +61,15 @@ jobs:
 
       - name: Minimize uv cache
         run: uv cache prune --ci
+
+  ci-lint-and-tests-all-passed:
+      runs-on: ubuntu-latest
+      needs: lint-and-test
+      if: always()
+      steps:
+        - name: All checks passed?
+          run: |
+            if [ "${{ needs.lint-and-test.result }}" != "success" ]; then
+              echo "Matrix jobs failed!"
+              exit 1
+            fi
